### ISSUE TITLE
Provide default implementation if delegate is not implemented

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/SectionScrubber#17]
I think we can provide a default implementation instead of using an extension implementation for the delegate, this would help so people don't need to set a delegate unless they _really_ need it.

(I'll elaborate more later)

**Comment by marijnschilling** [comment]
Hmm I'm not sure I think if you add a view to your collectionView (the sectionScrubber in this case) you don't want it to secretly be able to control the contentOffset of you collectionView. I think by implementing a delegate you make it clear that you give the view bigger responsibility...

But I would be interested in how you would do that, would you set the collectionView a s a property on the dateScrubber?
