### ISSUE TITLE
Container view blocks touches bellow it

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/SectionScrubber#45]
# Steps to reproduce

Try tapping a cell in the same y position as the scrubber and touches will be ignored.

**Comment by 3lvis** [comment]
The SectionScrubber view blocks touches bellow it.

**Comment by elland** [comment]
Even when invisible? We can set it to `isUserInteractionEnabled = false` if it's hidden, that should solve it.

**Comment by elland** [comment]
@3lvis There are _no_ actions for tapping a cell. Maybe _that's_ the issue??

**Comment by 3lvis** [comment]
Add an action to the cell, then make the scrubber(view)'s background color to red and you'll see how it blocks.

**Comment by elland** [comment]
NO idea what you meant now. 😢

**Comment by elland** [comment]
After I added an action to the cell, I can't reproduce it. If scrubber leaves the screen, I can tap everything.

**Comment by 3lvis** [comment]
https://github.com/bakkenbaeck/SectionScrubber/pull/46

**Comment by 3lvis** [comment]
<img width="487" alt="screen shot 2016-10-17 at 9 37 36 am" src="https://cloud.githubusercontent.com/assets/1088217/19428943/5a858b2a-944d-11e6-85a6-f1ca948649f8.png">

**Comment by elland** [comment]
Checking now.
