### ISSUE TITLE
Hiding the sectionLabel after delay is not performed while scrolling the collectionView

### ISSUE THREAD

**Issue by marijnschilling** [bakkenbaeck/SectionScrubber#7]
To reproduce:
1. Use the dateScrubber to scrub over the collectionView so the sectionLabel appears
2. Release the date scrubber
3. Scroll the collectionView
4. The sectionLabel stays visible while scrolling the collectionView, while it should disappear 3 seconds after releasing the dateScrubber

**Comment by 3lvis** [comment]
Just gave it a try, it isn't too bad. Some might even consider it a feature. 😁

**Comment by marijnschilling** [comment]
Haha yeah it could be a feature :D But I think something is going wrong with the `performSelector: withObject: afterDelay:` can't seem to control when it actually get's performed... 🤔

**Comment by 3lvis** [comment]
Haven't been able to verify this myself.
